name: Workflow calling reusable workflow

on:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: echo message
      run: echo "Hi, I am starter workflow"
  Call_reusable_workflow:
    uses: Moswin-jebaraj/Reusable_worflows/.github/workflows/reusable_workflow.yml@v1
